// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlSw89MmZnlwxRhDyiOfNnHEfDjQgFQO8',
    appId: '1:198287293546:web:1493bcf8fe3686b8ac1e13',
    messagingSenderId: '198287293546',
    projectId: 'campju-345fe',
    authDomain: 'campju-345fe.firebaseapp.com',
    storageBucket: 'campju-345fe.firebasestorage.app',
    measurementId: 'G-Z3JN280T86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-kn9uslNkWZ9oh0CEbXqNCAoUcITAaWg',
    appId: '1:198287293546:android:b879f52eb72ef26eac1e13',
    messagingSenderId: '198287293546',
    projectId: 'campju-345fe',
    storageBucket: 'campju-345fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn7Yg_7G4nY69xd9waNdSUl_VaQSBUSOc',
    appId: '1:198287293546:ios:d9623043aadd2a88ac1e13',
    messagingSenderId: '198287293546',
    projectId: 'campju-345fe',
    storageBucket: 'campju-345fe.firebasestorage.app',
    iosClientId: '198287293546-l9dl0sltai57n2flnqbrqu4tphhktksr.apps.googleusercontent.com',
    iosBundleId: 'com.example.campju',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn7Yg_7G4nY69xd9waNdSUl_VaQSBUSOc',
    appId: '1:198287293546:ios:d9623043aadd2a88ac1e13',
    messagingSenderId: '198287293546',
    projectId: 'campju-345fe',
    storageBucket: 'campju-345fe.firebasestorage.app',
    iosClientId: '198287293546-l9dl0sltai57n2flnqbrqu4tphhktksr.apps.googleusercontent.com',
    iosBundleId: 'com.example.campju',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlSw89MmZnlwxRhDyiOfNnHEfDjQgFQO8',
    appId: '1:198287293546:web:0776a4e51e968878ac1e13',
    messagingSenderId: '198287293546',
    projectId: 'campju-345fe',
    authDomain: 'campju-345fe.firebaseapp.com',
    storageBucket: 'campju-345fe.firebasestorage.app',
    measurementId: 'G-LGP8MGYCLM',
  );
}
